-- 회원(User) 테이블 생성
-- DESIGN-001의 핵심 설계 결정("DB 유니크 제약을 정합성의 최종 방어선으로 사용")을
-- 실제 스키마에 명시적으로 반영한다.
-- Hibernate ddl-auto 설정과 무관하게, 운영/테스트 환경 모두 이 마이그레이션을 통해
-- users.email 컬럼에 UNIQUE 제약이 존재함을 보장한다.
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL,
    password_hash     VARCHAR(255) NOT NULL,
    nickname          VARCHAR(255) NOT NULL,
    risk_profile      VARCHAR(20)  NOT NULL,
    investment_period VARCHAR(20)  NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);
